Class EPCIS.BO.getSubscriptionIDsResponse Extends Ens.Response [ ProcedureBlock ]
{

Property string As list Of %String;

Storage Default
{
<Data name="getSubscriptionIDsResponseDefaultData">
<Subscript>"getSubscriptionIDsResponse"</Subscript>
<Value name="1">
<Value>string</Value>
</Value>
</Data>
<DefaultData>getSubscriptionIDsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
