Class EPCIS.BO.getStandardVersionResponse Extends Ens.Response [ ProcedureBlock ]
{

Property GetStandardVersionResult As %String;

Storage Default
{
<Data name="getStandardVersionResponseDefaultData">
<Subscript>"getStandardVersionResponse"</Subscript>
<Value name="1">
<Value>GetStandardVersionResult</Value>
</Value>
</Data>
<DefaultData>getStandardVersionResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
