/// ISO 639-2; 1998 representation of Language name. Refer to http://www.loc.gov/standards/iso639-2/iso639jac.html to get the latest version of the standard.
/// Created from: c:/temp/epcis/basictypes.xsd
Class EPCIS.sbdh.Language Extends %String [ ProcedureBlock, SqlTableName = _Language ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter MAXLEN;

Parameter NAMESPACE = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader";

}
