/// Created from: c:/temp/epcis/epcglobal-epcis-query-1_2.xsd
Class EPCIS.epcisq.VoidHolder Extends (%SerialObject, %XML.Adaptor) [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 0;

Parameter NAMESPACE = "urn:epcglobal:epcis-query:xsd:1";

Parameter XMLNAME = "VoidHolder";

Parameter XMLSEQUENCE = 1;

Storage Default
{
<StreamLocation>^EPCIS.epcisq.VoidHolderS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
