/// 
Class EPCIS.intersystems.HL7MessageRouterRoutingRule Extends Ens.Rule.Definition
{

Parameter RuleAssistClass = "EnsLib.HL7.MsgRouter.RuleAssist";

XData RuleDefinition [ XMLNamespace = "http://www.intersystems.com/rule" ]
{
<ruleDefinition alias="EPCIS.intersystems.HL7 Message RouterRoutingRule" context="EnsLib.HL7.MsgRouter.RoutingEngine" production="EPCIS.intersystems.Production">
<ruleSet name="" effectiveBegin="" effectiveEnd="">
<rule name="">
</rule>
</ruleSet>
</ruleDefinition>
}

}
